<?php
namespace App\Controllers; use App\Support\Jwt;
final class AdminController {
 public function overview():never{$this->admin();$stats=['users'=>(int)db()->query("SELECT COUNT(*) FROM users WHERE role='user'")->fetchColumn(),'companies'=>(int)db()->query("SELECT COUNT(*) FROM companies")->fetchColumn(),'revenue'=>(int)db()->query("SELECT COALESCE(SUM(amount),0) FROM transactions WHERE status='successful'")->fetchColumn(),'active_subscriptions'=>(int)db()->query("SELECT COUNT(*) FROM subscriptions WHERE status='active' AND expires_at>NOW()")->fetchColumn(),'trials'=>(int)db()->query("SELECT COUNT(*) FROM subscriptions WHERE source='trial'")->fetchColumn()];jsonResponse(['stats'=>$stats]);}
 public function users():never{$this->admin();$r=db()->query("SELECT u.id,u.mobile,u.first_name,u.last_name,u.email,u.created_at,c.name company_name,c.industry,(SELECT COUNT(*) FROM subscriptions s WHERE s.user_id=u.id) subscriptions_count FROM users u LEFT JOIN companies c ON c.user_id=u.id WHERE u.role='user' ORDER BY u.id DESC")->fetchAll();jsonResponse(['data'=>$r]);}
 public function packages():never{$this->admin();if($_SERVER['REQUEST_METHOD']==='POST'){$d=body();$id=(int)($d['id']??0);$v=[trim($d['name']??''),trim($d['slug']??''),trim($d['description']??''),(int)($d['price']??0),(int)($d['duration_days']??30),($d['usage_limit']??'')===''?null:(int)$d['usage_limit'],!empty($d['is_featured']),isset($d['is_active'])?(bool)$d['is_active']:true,json_encode($d['features']??[],JSON_UNESCAPED_UNICODE)];if($id){$v[]=$id;db()->prepare("UPDATE packages SET name=?,slug=?,description=?,price=?,duration_days=?,usage_limit=?,is_featured=?,is_active=?,features=? WHERE id=?")->execute($v);}else db()->prepare("INSERT INTO packages(name,slug,description,price,duration_days,usage_limit,is_featured,is_active,features)VALUES(?,?,?,?,?,?,?,?,?)")->execute($v);jsonResponse(['message'=>'پکیج ذخیره شد.']);}$r=db()->query("SELECT * FROM packages ORDER BY id DESC")->fetchAll();foreach($r as&$x)$x['features']=json_decode($x['features'],true);jsonResponse(['data'=>$r]);}
 public function orders():never{$this->admin();$r=db()->query("SELECT o.id,o.order_number,o.amount,o.status,o.created_at,p.name package_name,CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,'')) user_name,u.mobile,t.status transaction_status,t.reference_id FROM orders o JOIN users u ON u.id=o.user_id JOIN packages p ON p.id=o.package_id LEFT JOIN transactions t ON t.order_id=o.id ORDER BY o.id DESC")->fetchAll();jsonResponse(['data'=>$r]);}
 public function subscriptions():never{$this->admin();if($_SERVER['REQUEST_METHOD']==='PUT'){$d=body();$s=in_array($d['status']??'',['active','expired','cancelled'],true)?$d['status']:'cancelled';db()->prepare("UPDATE subscriptions SET status=? WHERE id=?")->execute([$s,(int)($d['id']??0)]);jsonResponse(['message'=>'وضعیت اشتراک تغییر کرد.']);}$r=db()->query("SELECT s.*,p.name package_name,u.mobile,CONCAT(COALESCE(u.first_name,''),' ',COALESCE(u.last_name,'')) user_name FROM subscriptions s JOIN users u ON u.id=s.user_id JOIN packages p ON p.id=s.package_id ORDER BY s.id DESC")->fetchAll();jsonResponse(['data'=>$r]);}
 private function admin():int{$id=Jwt::userId();if(!$id)jsonResponse(['message'=>'نیاز به ورود دارید.'],401);$q=db()->prepare("SELECT role FROM users WHERE id=?");$q->execute([$id]);if($q->fetchColumn()!=='admin')jsonResponse(['message'=>'دسترسی مدیر لازم است.'],403);return$id;}
}
