<?php
namespace App\Controllers; use App\Support\Jwt;
final class OnboardingController {
 public function status():never{$id=$this->uid();$q=db()->prepare("SELECT id,mobile,first_name,last_name,email,job_title,role,onboarding_step FROM users WHERE id=?");$q->execute([$id]);$u=$q->fetch();$q=db()->prepare("SELECT name,industry,employee_count FROM companies WHERE user_id=?");$q->execute([$id]);jsonResponse(['user'=>$u,'company'=>$q->fetch()?:null,'next_step'=>(int)$u['onboarding_step']]);}
 public function userInfo():never{$id=$this->uid();$d=body();$f=trim($d['first_name']??'');$l=trim($d['last_name']??'');$e=trim($d['email']??'');if(mb_strlen($f)<2||mb_strlen($l)<2)jsonResponse(['message'=>'نام و نام خانوادگی را کامل وارد کنید.'],422);if($e&&!filter_var($e,FILTER_VALIDATE_EMAIL))jsonResponse(['message'=>'ایمیل معتبر نیست.'],422);db()->prepare("UPDATE users SET first_name=?,last_name=?,email=?,onboarding_step=GREATEST(onboarding_step,2) WHERE id=?")->execute([$f,$l,$e?:null,$id]);jsonResponse(['message'=>'اطلاعات کاربری ذخیره شد.','next_step'=>2]);}
 public function company():never{$id=$this->uid();$d=body();$n=trim($d['name']??'');$i=trim($d['industry']??'');$c=(int)($d['employee_count']??0);$j=trim($d['job_title']??'');if(mb_strlen($n)<2||!$i||$c<1||!$j)jsonResponse(['message'=>'تمام مشخصات شرکت را کامل وارد کنید.'],422);db()->beginTransaction();db()->prepare("INSERT INTO companies(user_id,name,industry,employee_count)VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),industry=VALUES(industry),employee_count=VALUES(employee_count)")->execute([$id,$n,$i,$c]);db()->prepare("UPDATE users SET job_title=?,onboarding_step=3,onboarding_completed_at=NOW() WHERE id=?")->execute([$j,$id]);db()->commit();jsonResponse(['message'=>'مشخصات شرکت ذخیره شد.','next_step'=>3]);}
 public function profile():never{$id=$this->uid();if($_SERVER['REQUEST_METHOD']==='PUT'){$d=body();db()->prepare("UPDATE users SET first_name=?,last_name=?,email=?,job_title=? WHERE id=?")->execute([trim($d['first_name']??''),trim($d['last_name']??''),trim($d['email']??'')?:null,trim($d['job_title']??''),$id]);jsonResponse(['message'=>'پروفایل ذخیره شد.']);}$q=db()->prepare("SELECT id,mobile,first_name,last_name,email,job_title FROM users WHERE id=?");$q->execute([$id]);jsonResponse(['data'=>$q->fetch()]);}
 private function uid():int{$id=Jwt::userId();if(!$id)jsonResponse(['message'=>'نیاز به ورود دارید.'],401);return$id;}
}
