<?php
namespace App\Controllers; use App\Support\Jwt;
final class ShopController {
 public function packages():never{$r=db()->query("SELECT * FROM packages WHERE is_active=1 ORDER BY price")->fetchAll();foreach($r as&$x)$x['features']=json_decode($x['features'],true);jsonResponse(['data'=>$r]);}
 public function trial():never{$u=$this->uid();$q=db()->prepare("SELECT onboarding_step FROM users WHERE id=?");$q->execute([$u]);if((int)$q->fetchColumn()<3)jsonResponse(['message'=>'ابتدا اطلاعات کاربری و شرکت را تکمیل کنید.'],422);$q=db()->prepare("SELECT COUNT(*) FROM subscriptions WHERE user_id=? AND source='trial'");$q->execute([$u]);if($q->fetchColumn())jsonResponse(['message'=>'دوره آزمایشی قبلاً برای شما فعال شده است.'],409);$p=db()->query("SELECT * FROM packages WHERE slug='trial' AND is_active=1 LIMIT 1")->fetch();db()->prepare("INSERT INTO subscriptions(user_id,package_id,source,starts_at,expires_at,usage_limit)VALUES(?,?,'trial',NOW(),DATE_ADD(NOW(),INTERVAL 5 DAY),?)")->execute([$u,$p['id'],$p['usage_limit']]);jsonResponse(['message'=>'دوره آزمایشی ۵ روزه فعال شد.'],201);}
 public function order():never{$u=$this->uid();$q=db()->prepare("SELECT onboarding_step FROM users WHERE id=?");$q->execute([$u]);if((int)$q->fetchColumn()<3)jsonResponse(['message'=>'ابتدا اطلاعات کاربری و شرکت را تکمیل کنید.'],422);$d=body();$q=db()->prepare("SELECT * FROM packages WHERE id=? AND is_active=1 AND price>0");$q->execute([(int)($d['package_id']??0)]);$p=$q->fetch();if(!$p)jsonResponse(['message'=>'پکیج قابل خرید یافت نشد.'],404);$no='ORD-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));db()->prepare("INSERT INTO orders(user_id,package_id,order_number,amount)VALUES(?,?,?,?)")->execute([$u,$p['id'],$no,$p['price']]);$oid=(int)db()->lastInsertId();$a='sandbox-'.bin2hex(random_bytes(8));db()->prepare("INSERT INTO transactions(order_id,user_id,gateway,authority,amount)VALUES(?,?,'sandbox',?,?)")->execute([$oid,$u,$a,$p['price']]);jsonResponse(['order_id'=>$oid,'order_number'=>$no,'payment_url'=>env('APP_URL').'/api/payments/callback?authority='.$a],201);}
 public function callback():never{$a=$_GET['authority']??'';$q=db()->prepare("SELECT t.*,o.package_id,p.duration_days,p.usage_limit FROM transactions t JOIN orders o ON o.id=t.order_id JOIN packages p ON p.id=o.package_id WHERE t.authority=? LIMIT 1");$q->execute([$a]);$t=$q->fetch();if(!$t)jsonResponse(['message'=>'تراکنش یافت نشد.'],404);if($t['status']!=='successful'){db()->beginTransaction();db()->prepare("UPDATE transactions SET status='successful',reference_id=?,paid_at=NOW() WHERE id=?")->execute(['REF-'.time(),$t['id']]);db()->prepare("UPDATE orders SET status='paid' WHERE id=?")->execute([$t['order_id']]);db()->prepare("INSERT INTO subscriptions(user_id,package_id,order_id,source,starts_at,expires_at,usage_limit)VALUES(?,?,?,'purchase',NOW(),DATE_ADD(NOW(),INTERVAL ? DAY),?)")->execute([$t['user_id'],$t['package_id'],$t['order_id'],$t['duration_days'],$t['usage_limit']]);db()->commit();}header('Location: '.env('FRONTEND_URL').'/dashboard?payment=success');exit;}
 public function dashboard():never{$u=$this->uid();$q=db()->prepare("SELECT u.id,u.mobile,u.first_name,u.last_name,u.email,u.job_title,u.role,c.name company_name,c.industry,c.employee_count FROM users u LEFT JOIN companies c ON c.user_id=u.id WHERE u.id=?");$q->execute([$u]);$user=$q->fetch();$q=db()->prepare("SELECT s.*,p.name package_name,p.price,ROUND(s.usage_used/NULLIF(s.usage_limit,0)*100) usage_percent FROM subscriptions s JOIN packages p ON p.id=s.package_id WHERE s.user_id=? ORDER BY s.id DESC");$q->execute([$u]);$subs=$q->fetchAll();$q=db()->prepare("SELECT t.id,t.amount,t.status,t.reference_id,t.paid_at,o.order_number,p.name package_name FROM transactions t JOIN orders o ON o.id=t.order_id JOIN packages p ON p.id=o.package_id WHERE t.user_id=? ORDER BY t.id DESC");$q->execute([$u]);jsonResponse(['user'=>$user,'subscriptions'=>$subs,'transactions'=>$q->fetchAll()]);}
 public function invoice(int$id):never{$u=$this->uid();$q=db()->prepare("SELECT t.*,o.order_number,p.name package_name,u.first_name,u.last_name,u.mobile FROM transactions t JOIN orders o ON o.id=t.order_id JOIN packages p ON p.id=o.package_id JOIN users u ON u.id=t.user_id WHERE t.id=? AND t.user_id=? AND t.status='successful'");$q->execute([$id,$u]);$x=$q->fetch();if(!$x)jsonResponse(['message'=>'فاکتور یافت نشد.'],404);header('Content-Type:text/html; charset=utf-8');header('Content-Disposition:attachment; filename=invoice-'.$x['order_number'].'.html');echo '<!doctype html><meta charset="utf-8"><body dir="rtl" style="font-family:Tahoma;padding:40px"><h1>فاکتور فروش</h1><p>شماره سفارش: '.htmlspecialchars($x['order_number']).'</p><p>مشتری: '.htmlspecialchars(trim($x['first_name'].' '.$x['last_name'])).'</p><p>پکیج: '.htmlspecialchars($x['package_name']).'</p><p>مبلغ: '.number_format((int)$x['amount']).' تومان</p><p>پیگیری: '.htmlspecialchars($x['reference_id']).'</p></body>';exit;}
 private function uid():int{$id=Jwt::userId();if(!$id)jsonResponse(['message'=>'نیاز به ورود دارید.'],401);return$id;}
}
