CREATE DATABASE IF NOT EXISTS product_dashboard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE product_dashboard;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,mobile VARCHAR(11) UNIQUE NOT NULL,first_name VARCHAR(80),last_name VARCHAR(80),email VARCHAR(190),job_title VARCHAR(120),role ENUM('user','admin') NOT NULL DEFAULT 'user',onboarding_step TINYINT UNSIGNED DEFAULT 1,onboarding_completed_at DATETIME,mobile_verified_at DATETIME,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE otp_codes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,mobile VARCHAR(11) NOT NULL,purpose ENUM('login','payment','profile') DEFAULT 'login',code_hash VARCHAR(255) NOT NULL,status ENUM('sent','verified','expired','blocked','failed') DEFAULT 'sent',attempts TINYINT UNSIGNED DEFAULT 0,provider_message_id VARCHAR(120),expires_at DATETIME NOT NULL,verified_at DATETIME,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_otp(mobile,created_at));
CREATE TABLE sms_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,mobile VARCHAR(11) NOT NULL,provider VARCHAR(30),template_code VARCHAR(100),provider_message_id VARCHAR(120),status ENUM('queued','sent','delivered','failed'),request_payload JSON,response_payload JSON,error_code VARCHAR(80),error_message VARCHAR(500),created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE packages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,slug VARCHAR(140) UNIQUE NOT NULL,description TEXT,price BIGINT UNSIGNED DEFAULT 0,duration_days INT UNSIGNED NOT NULL,usage_limit INT UNSIGNED,is_featured BOOLEAN DEFAULT FALSE,is_active BOOLEAN DEFAULT TRUE,features JSON NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE companies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED UNIQUE NOT NULL,name VARCHAR(160) NOT NULL,industry VARCHAR(120) NOT NULL,employee_count INT UNSIGNED NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,package_id BIGINT UNSIGNED NOT NULL,order_number VARCHAR(32) UNIQUE NOT NULL,amount BIGINT UNSIGNED NOT NULL,status ENUM('pending','paid','failed','cancelled') DEFAULT 'pending',created_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(package_id) REFERENCES packages(id));
CREATE TABLE transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,gateway VARCHAR(40),authority VARCHAR(150),reference_id VARCHAR(150),amount BIGINT UNSIGNED,status ENUM('initiated','successful','failed','refunded') DEFAULT 'initiated',raw_response JSON,paid_at DATETIME,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_ref(gateway,reference_id),FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE subscriptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,package_id BIGINT UNSIGNED NOT NULL,order_id BIGINT UNSIGNED NULL,source ENUM('trial','purchase','admin') DEFAULT 'purchase',status ENUM('active','expired','cancelled') DEFAULT 'active',starts_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,usage_limit INT UNSIGNED,usage_used INT UNSIGNED DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(package_id) REFERENCES packages(id),FOREIGN KEY(order_id) REFERENCES orders(id));
INSERT INTO packages(name,slug,description,price,duration_days,usage_limit,is_featured,is_active,features) VALUES
('آزمایشی ۵ روزه','trial','دسترسی آزمایشی برای بررسی امکانات',0,5,NULL,0,1,JSON_ARRAY('تمام امکانات پایه','بدون نیاز به پرداخت','فعال‌سازی فوری')),
('تیک‌آف ابری','takeoff','مناسب تیم‌های کوچک',799000,30,1000,1,1,JSON_ARRAY('مدیریت مشتریان','مدیریت فروش','ذخیره‌سازی ۷ گیگابایت')),
('پرواز اوج ابری','flight','مناسب کسب‌وکارهای در حال رشد',1099000,30,3000,0,1,JSON_ARRAY('اتوماسیون فروش','گزارش‌های پیشرفته','ذخیره‌سازی ۱۵ گیگابایت')),
('صعود اوج ابری','climb','مناسب سازمان‌های بزرگ',4899000,365,NULL,0,1,JSON_ARRAY('تمام ماژول‌ها','کاربر نامحدود','پشتیبانی اختصاصی'));
INSERT INTO users(mobile,first_name,last_name,role,onboarding_step,onboarding_completed_at,mobile_verified_at) VALUES('09120000000','مدیر','سیستم','admin',3,NOW(),NOW());
